#!/usr/bin/env bun
/**
 * design-tokens-gen — Specialist #2 of /senior-designer.
 *
 * Reads BRIEF + MOODBOARD, proposes a senior-grade globals.css with @theme,
 * modular spacing scale, differentiated radius, named easings, and utility
 * classes that exploit variable font axes.
 *
 * Usage:
 *   bun scripts/design-tokens-gen.ts <project-path> [--dry-run] [--from=<moodboard>]
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

interface Args {
  projectPath: string;
  dryRun: boolean;
  from?: string;
}

interface TokenProposal {
  colors: Array<{ name: string; value: string }>;
  fonts: { display: string; sans: string; mono: string };
  spacingScale: number[];
  radii: Array<{ name: string; value: string }>;
  shadows: Array<{ name: string; value: string }>;
  easings: Array<{ name: string; value: string }>;
  durations: Array<{ name: string; value: string }>;
  warnings: string[];
}

function parseArgs(argv: string[]): Args {
  const args: Args = {
    projectPath: resolve(argv[2] ?? process.cwd()),
    dryRun: false,
  };
  for (const a of argv.slice(3)) {
    if (a === "--dry-run") args.dryRun = true;
    else if (a.startsWith("--from=")) args.from = a.slice(7);
  }
  return args;
}

function modularScale(base: number, ratio: number, count: number): number[] {
  return Array.from({ length: count }, (_, i) => Math.round(base * ratio ** i * 100) / 100);
}

function buildProposal(moodboardText: string | null): TokenProposal {
  const warnings: string[] = [];
  const mood = (moodboardText ?? "").toLowerCase();

  const isDark = /dark|nocturne|noir/.test(mood);
  const isWarm = /warm|chaud|sépia|sepia|terracotta|ember/.test(mood);
  const isEditorial = /editorial|magazine|fraunces|serif/.test(mood);
  const isBrutalist = /brutalist|raw|kinetic/.test(mood);

  const accent = isWarm ? "#a8351a" : isBrutalist ? "#ff3d00" : "#1f5fff";
  const ink = isDark ? "#f5f0e6" : "#0e0c0a";
  const paper = isDark ? "#0e0c0a" : isWarm ? "#efe6d4" : "#f7f6f3";

  const colors: TokenProposal["colors"] = [
    { name: "--color-ink", value: ink },
    { name: "--color-ink-soft", value: isDark ? "#cfc6b3" : "#1c1814" },
    { name: "--color-paper", value: paper },
    { name: "--color-paper-deep", value: isWarm ? "#e6dac1" : "#ecebe6" },
    { name: "--color-accent", value: accent },
    { name: "--color-accent-soft", value: isWarm ? "#b94d2c" : "#3a78ff" },
    { name: "--color-neutral-quiet", value: isDark ? "#3a3530" : "#6a5d4c" },
  ];
  if (colors.length > 8) warnings.push("Color count exceeds doctrine 8 max");

  const display = isEditorial ? "Fraunces" : isBrutalist ? "Migra" : "PP Neue Montreal";
  const sans = isBrutalist || isEditorial ? "General Sans" : "Satoshi";
  const mono = "Geist Mono";

  return {
    colors,
    fonts: { display, sans, mono },
    spacingScale: modularScale(8, 1.25, 10),
    radii: [
      { name: "--radius-image", value: "0" },
      { name: "--radius-button", value: "6px" },
      { name: "--radius-card", value: "12px" },
      { name: "--radius-pill", value: "999px" },
    ],
    shadows: [
      { name: "--shadow-flat", value: "0 1px 0 0 rgb(0 0 0 / 0.04)" },
      { name: "--shadow-card", value: "0 8px 24px -12px rgb(0 0 0 / 0.12), 0 2px 4px -2px rgb(0 0 0 / 0.06)" },
      { name: "--shadow-hover", value: "0 16px 40px -16px rgb(0 0 0 / 0.18), 0 4px 8px -4px rgb(0 0 0 / 0.08)" },
    ],
    easings: [
      { name: "--ease-quart", value: "cubic-bezier(0.25, 1, 0.5, 1)" },
      { name: "--ease-expo", value: "cubic-bezier(0.16, 1, 0.3, 1)" },
      { name: "--ease-back", value: "cubic-bezier(0.34, 1.56, 0.64, 1)" },
      { name: "--ease-spring", value: "cubic-bezier(0.5, 0, 0, 1.25)" },
    ],
    durations: [
      { name: "--dur-fast", value: "180ms" },
      { name: "--dur-base", value: "320ms" },
      { name: "--dur-slow", value: "640ms" },
    ],
    warnings,
  };
}

function renderCss(p: TokenProposal): string {
  const lines: string[] = [];
  lines.push(`@import "tailwindcss";`, "");
  lines.push(`/* Generated by senior-designer design-tokens-gen */`, "");
  lines.push(`@theme {`);
  for (const c of p.colors) lines.push(`  ${c.name}: ${c.value};`);
  lines.push("");
  lines.push(`  --font-display: var(--font-${p.fonts.display.toLowerCase().replace(/\s+/g, "-")}), Georgia, serif;`);
  lines.push(`  --font-sans: var(--font-${p.fonts.sans.toLowerCase().replace(/\s+/g, "-")}), system-ui, sans-serif;`);
  lines.push(`  --font-mono: var(--font-${p.fonts.mono.toLowerCase().replace(/\s+/g, "-")}), ui-monospace, monospace;`);
  lines.push("");
  p.spacingScale.forEach((s, i) => lines.push(`  --space-${i + 1}: ${s}px;`));
  lines.push("");
  for (const r of p.radii) lines.push(`  ${r.name}: ${r.value};`);
  lines.push("");
  for (const s of p.shadows) lines.push(`  ${s.name}: ${s.value};`);
  lines.push("");
  for (const e of p.easings) lines.push(`  ${e.name}: ${e.value};`);
  lines.push("");
  for (const d of p.durations) lines.push(`  ${d.name}: ${d.value};`);
  lines.push(`}`, "");
  lines.push(`html { background: var(--color-paper); color: var(--color-ink); -webkit-font-smoothing: antialiased; text-rendering: geometricPrecision; }`, "");
  lines.push(`body { font-family: var(--font-sans); font-size: 1rem; line-height: 1.55; font-feature-settings: "ss01", "ss02"; }`, "");
  lines.push(`::selection { background: var(--color-ink); color: var(--color-paper); }`, "");
  if (p.fonts.display === "Fraunces") {
    lines.push(
      `.serif-xl { font-family: var(--font-display); font-variation-settings: "opsz" 144, "SOFT" 100, "WONK" 0; letter-spacing: -0.04em; font-weight: 400; }`,
      `.serif-italic { font-family: var(--font-display); font-variation-settings: "opsz" 144, "SOFT" 90, "WONK" 1; font-style: italic; }`,
      `.serif-mid { font-family: var(--font-display); font-variation-settings: "opsz" 72, "SOFT" 60, "WONK" 0; letter-spacing: -0.02em; }`,
      `.italic-wonky { font-style: italic; font-variation-settings: "opsz" 96, "SOFT" 50, "WONK" 1; }`,
      "",
    );
  }
  lines.push(
    `.mono { font-family: var(--font-mono); font-feature-settings: "ss01"; }`,
    `.caps { text-transform: uppercase; letter-spacing: 0.22em; }`,
    "",
    `@media (prefers-reduced-motion: reduce) {`,
    `  *, *::before, *::after { animation-duration: 0.001ms !important; animation-iteration-count: 1 !important; transition-duration: 0.001ms !important; }`,
    `}`,
    "",
  );
  return lines.join("\n");
}

function main(): void {
  const args = parseArgs(process.argv);
  const moodPath = args.from ?? join(args.projectPath, "docs/MOODBOARD.md");
  const moodboard = existsSync(moodPath) ? readFileSync(moodPath, "utf8") : null;
  if (!moodboard) {
    console.error("note: no MOODBOARD.md found, using defaults");
  }

  const proposal = buildProposal(moodboard);
  const css = renderCss(proposal);

  const target = join(args.projectPath, "src/app/globals.css");
  if (args.dryRun) {
    console.log("--- proposed globals.css ---");
    console.log(css);
    console.log("--- end ---");
    console.log(`\nVERDICT: ${proposal.warnings.length === 0 ? "OK" : "GAPS"} (dry-run, no write)`);
    for (const w of proposal.warnings) console.log(`  warning: ${w}`);
    return;
  }

  if (existsSync(target)) {
    const backup = target.replace(/\.css$/, `.backup-${Date.now()}.css`);
    writeFileSync(backup, readFileSync(target, "utf8"));
    console.log(`backup: ${backup}`);
  }
  writeFileSync(target, css);
  console.log(`wrote: ${target}`);
  console.log(`VERDICT: ${proposal.warnings.length === 0 ? "OK" : "GAPS"}`);
}

main();
